services:
  php:
    # image: 'fitopero/laravel_apache_node:latest'
    # environment:
    #     WWWGROUP: '${APP_NAME}'
    #     PROJECT_NAME: '${APP_NAME}'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${APP_NAME}'
        PROJECT_NAME: '${APP_NAME}'
    ports:
      - '80:80'
      - '5173:5173'
    volumes:
      - '.:/var/www/html/${APP_NAME}'
    networks:
      - project
    depends_on:
      - mysql
      - redis
      - mailpit
      - mongodb
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:${DB_PORT}'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'data_mysql:/var/lib/mysql'
    networks:
      - project
  mongodb:
    image: 'mongo'
    environment:
        MONGO_INITDB_ROOT_USERNAME: '${DB_MONGO_USERNAME}'
        MONGO_INITDB_ROOT_PASSWORD: '${DB_MONGO_PASSWORD}'
    ports:
        - '27017:${DB_MONGO_PORT}'
    volumes:
        - 'data_mongodb:/data/db'
    networks:
        - project
  redis:
    image: 'redis:alpine'
    ports:
        - '6379:6379'
    volumes:
        - 'data-redis:/data'
    networks:
        - project
    healthcheck:
        test:
            - CMD
            - redis-cli
            - ping
        retries: 3
        timeout: 5s
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
        - '1025:1025'
        - '8025:8025'
    networks:
        - project
networks:
  project:
    driver: bridge
volumes:
  data_mysql:
    driver: local
  data-redis:
    driver: local
  data_mongodb:
    driver: local
